### ISSUE TITLE
err

### ISSUE THREAD

**Issue by i3bdulr7man** [jamaljeantobias/gatsby-source-hubspot-forms#4]
ERROR #11321  PLUGIN

"gatsby-source-hubspot-forms" threw an error while running the sourceNodes lifecycle:

TypeError: Cannot destructure property 'createNode' of 'boundActionCreators' as it is undefined.

  52 |     return
  53 |   } catch (err) {
> 54 |     throw new Error(err)
     |           ^
  55 |   }
  56 | }
  57 |

File: node_modules\gatsby-source-hubspot-forms\gatsby-node.js:54:11

**Comment by natac13** [comment]
https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#removal-of-boundactioncreators
